# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20171216_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
