# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurantlocation_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
